ServerEvents.recipes(event => {
    event.remove('butcher:jarrecipe')
    event.remove('butcher:pliers_recipe')
    event.remove('butcher:skinning_knife_recipe')
    event.remove(/butcher:.*dragon.*/)
    event.remove(/butcher:.*elder.*/)
    event.remove(/butcher:.*illager.*/)
    event.remove(/butcher:.*end.*/)
    event.remove(/butcher:.*shulker.*/)
    event.remove(/butcher:.*sniffer.*/)
    event.remove(/butcher:.*piglin.*/)
    event.remove(/butcher:.*evoker.*/)
    event.remove(/butcher:.*hoglin.*/)
    event.remove(/butcher:.*guardian.*/)
})