ServerEvents.tags('block', event => {
    // Tag with all the wooden roofs from "roads and roofs"
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/acacia')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/ash')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/aspen')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/birch')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/blackwood')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/chestnut')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/douglas_fir')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/hickory')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/kapok')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/mangrove')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/maple')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/oak')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/palm')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/pine')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/rosewood')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/sequoia')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/spruce')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/sycamore')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/white_cedar')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/willow')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/baobab')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/eucalyptus')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/mahogany')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/hevea')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/tualang')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/teak')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/cypress')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/fig')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/ironwood')
    event.add('materialism:wood_shingles_roofs','rnr:wood/shingles/ipe')
    // Tag with all the wattle colored variants from TFC
    event.add('materialism:wattle','tfc:wattle/unstained')
    event.add('materialism:wattle','tfc:wattle/white')
    event.add('materialism:wattle','tfc:wattle/orange')
    event.add('materialism:wattle','tfc:wattle/magenta')
    event.add('materialism:wattle','tfc:wattle/light_blue')
    event.add('materialism:wattle','tfc:wattle/yellow')
    event.add('materialism:wattle','tfc:wattle/lime')
    event.add('materialism:wattle','tfc:wattle/pink')
    event.add('materialism:wattle','tfc:wattle/gray')
    event.add('materialism:wattle','tfc:wattle/light_gray')
    event.add('materialism:wattle','tfc:wattle/cyan')
    event.add('materialism:wattle','tfc:wattle/purple')
    event.add('materialism:wattle','tfc:wattle/blue')
    event.add('materialism:wattle','tfc:wattle/brown')
    event.add('materialism:wattle','tfc:wattle/green')
    event.add('materialism:wattle','tfc:wattle/red')
    event.add('materialism:wattle','tfc:wattle/black')
    // Tag with all the gravel roads from "roads and roofs"
    event.add('materialism:gravel_roads','rnr:rock/gravel_road/granite')
    event.add('materialism:gravel_roads','rnr:rock/gravel_road/diorite')
    event.add('materialism:gravel_roads','rnr:rock/gravel_road/gabbro')
    event.add('materialism:gravel_roads','rnr:rock/gravel_road/shale')
    event.add('materialism:gravel_roads','rnr:rock/gravel_road/claystone')
    event.add('materialism:gravel_roads','rnr:rock/gravel_road/limestone')
    event.add('materialism:gravel_roads','rnr:rock/gravel_road/conglomerate')
    event.add('materialism:gravel_roads','rnr:rock/gravel_road/dolomite')
    event.add('materialism:gravel_roads','rnr:rock/gravel_road/chert')
    event.add('materialism:gravel_roads','rnr:rock/gravel_road/chalk')
    event.add('materialism:gravel_roads','rnr:rock/gravel_road/rhyolite')
    event.add('materialism:gravel_roads','rnr:rock/gravel_road/basalt')
    event.add('materialism:gravel_roads','rnr:rock/gravel_road/andesite')
    event.add('materialism:gravel_roads','rnr:rock/gravel_road/dacite')
    event.add('materialism:gravel_roads','rnr:rock/gravel_road/quartzite')
    event.add('materialism:gravel_roads','rnr:rock/gravel_road/slate')
    event.add('materialism:gravel_roads','rnr:rock/gravel_road/phyllite')
    event.add('materialism:gravel_roads','rnr:rock/gravel_road/schist')
    event.add('materialism:gravel_roads','rnr:rock/gravel_road/gneiss')
    event.add('materialism:gravel_roads','rnr:rock/gravel_road/marble')
    event.add('materialism:tier_i_roofs','rnr:thatch_roof')

    // Tags for each class' woods
    function addClassWoods(event, classTag, woods) {
        woods.forEach(wood => {
            const mod = getWoodMod(wood);
            event.add(`materialism:${classTag}_wood_planks`, `${mod}:wood/planks/${wood}`)
            event.add(`materialism:${classTag}_wood_logs`, `${mod}:wood/log/${wood}`)
            event.add(`materialism:${classTag}_wood_shingles`, `rnr:wood/shingles/${wood}`)
            event.add(`materialism:${classTag}_wood_shingles`, `rnr:wood/shingles/${wood}_stairs`)
            event.add(`materialism:${classTag}_wood_shingles`, `rnr:wood/shingles/${wood}_slab`)
            event.add(`materialism:${classTag}_wood_fences`, `${mod}:wood/planks/${wood}_fence`)
            event.add(`materialism:${classTag}_wood_fences`, `${mod}:wood/planks/${wood}_log_fence`)
            event.add(`materialism:${classTag}_wood_fences`, `mcw_tfc_aio:fences/${wood}_fences/${wood}_horse_fence`)
            event.add(`materialism:${classTag}_wood_fences`, `mcw_tfc_aio:fences/${wood}_fences/${wood}_picket_fence`)
            event.add(`materialism:${classTag}_wood_fences`, `mcw_tfc_aio:fences/${wood}_fences/${wood}_stockade_fence`)
            event.add(`materialism:${classTag}_furniture_stools`, `mcw_tfc_aio:furniture/${wood}_furniture/${wood}_stool_chair`)
            event.add(`materialism:${classTag}_furniture_stools`, `mcw_tfc_aio:furniture/${wood}_furniture/stripped_${wood}_stool_chair`)
            event.add(`materialism:${classTag}_furniture_chairs`, `mcw_tfc_aio:furniture/${wood}_furniture/${wood}_chair`)
            event.add(`materialism:${classTag}_furniture_chairs`, `mcw_tfc_aio:furniture/${wood}_furniture/${wood}_striped_chair`)
            event.add(`materialism:${classTag}_furniture_modern_chairs`, `mcw_tfc_aio:furniture/${wood}_furniture/${wood}_modern_chair`)
            event.add(`materialism:${classTag}_furniture_modern_chairs`, `mcw_tfc_aio:furniture/${wood}_furniture/stripped_${wood}_modern_chair`)
            event.add(`materialism:${classTag}_furniture_chairs`, `mcw_tfc_aio:furniture/${wood}_furniture/stripped_${wood}_chair`)
            event.add(`materialism:${classTag}_furniture_chairs`, `mcw_tfc_aio:furniture/${wood}_furniture/stripped_${wood}_striped_chair`)
            event.add(`materialism:${classTag}_furniture_tables`, `mcw_tfc_aio:furniture/${wood}_furniture/${wood}_table`)
            event.add(`materialism:${classTag}_furniture_tables`, `mcw_tfc_aio:furniture/${wood}_furniture/stripped_${wood}_table`)
            event.add(`materialism:${classTag}_furniture_tables`, `mcw_tfc_aio:furniture/${wood}_furniture/${wood}_end_table`)
            event.add(`materialism:${classTag}_furniture_tables`, `mcw_tfc_aio:furniture/${wood}_furniture/stripped_${wood}_end_table`)
            event.add(`materialism:${classTag}_furniture_glass_tables`, `mcw_tfc_aio:furniture/${wood}_furniture/${wood}_glass_table`)
            event.add(`materialism:${classTag}_furniture_glass_tables`, `mcw_tfc_aio:furniture/${wood}_furniture/stripped_${wood}_glass_table`)
            event.add(`materialism:${classTag}_furniture_wardrobes`, `mcw_tfc_aio:furniture/${wood}_furniture/${wood}_wardrobe`)
            event.add(`materialism:${classTag}_furniture_wardrobes`, `mcw_tfc_aio:furniture/${wood}_furniture/${wood}_modern_wardrobe`)
            event.add(`materialism:${classTag}_furniture_wardrobes`, `mcw_tfc_aio:furniture/${wood}_furniture/${wood}_double_wardrobe`)
            event.add(`materialism:${classTag}_furniture_wardrobes`, `mcw_tfc_aio:furniture/${wood}_furniture/${wood}_drawer`)
            event.add(`materialism:${classTag}_furniture_wardrobes`, `mcw_tfc_aio:furniture/${wood}_furniture/${wood}_double_drawer`)
            event.add(`materialism:${classTag}_furniture_wardrobes`, `mcw_tfc_aio:furniture/${wood}_furniture/${wood}_large_drawer`)
            event.add(`materialism:${classTag}_furniture_wardrobes`, `mcw_tfc_aio:furniture/${wood}_furniture/${wood}_triple_drawer`)
            event.add(`materialism:${classTag}_furniture_wardrobes`, `mcw_tfc_aio:furniture/${wood}_furniture/${wood}_lower_triple_drawer`)
            event.add(`materialism:${classTag}_furniture_wardrobes`, `mcw_tfc_aio:furniture/${wood}_furniture/${wood}_drawer_counter`)
            event.add(`materialism:${classTag}_furniture_wardrobes`, `mcw_tfc_aio:furniture/${wood}_furniture/${wood}_double_drawer_counter`)
            event.add(`materialism:${classTag}_furniture_wardrobes`, `mcw_tfc_aio:furniture/${wood}_furniture/${wood}_cupboard_counter`)
            event.add(`materialism:${classTag}_furniture_wardrobes`, `mcw_tfc_aio:furniture/${wood}_furniture/stripped_${wood}_wardrobe`)
            event.add(`materialism:${classTag}_furniture_wardrobes`, `mcw_tfc_aio:furniture/${wood}_furniture/stripped_${wood}_modern_wardrobe`)
            event.add(`materialism:${classTag}_furniture_wardrobes`, `mcw_tfc_aio:furniture/${wood}_furniture/stripped_${wood}_double_wardrobe`)
            event.add(`materialism:${classTag}_furniture_wardrobes`, `mcw_tfc_aio:furniture/${wood}_furniture/stripped_${wood}_drawer`)
            event.add(`materialism:${classTag}_furniture_wardrobes`, `mcw_tfc_aio:furniture/${wood}_furniture/stripped_${wood}_double_drawer`)
            event.add(`materialism:${classTag}_furniture_wardrobes`, `mcw_tfc_aio:furniture/${wood}_furniture/stripped_${wood}_large_drawer`)
            event.add(`materialism:${classTag}_furniture_wardrobes`, `mcw_tfc_aio:furniture/${wood}_furniture/stripped_${wood}_triple_drawer`)
            event.add(`materialism:${classTag}_furniture_wardrobes`, `mcw_tfc_aio:furniture/${wood}_furniture/stripped_${wood}_lower_triple_drawer`)
            event.add(`materialism:${classTag}_furniture_wardrobes`, `mcw_tfc_aio:furniture/${wood}_furniture/stripped_${wood}_drawer_counter`)
            event.add(`materialism:${classTag}_furniture_wardrobes`, `mcw_tfc_aio:furniture/${wood}_furniture/stripped_${wood}_double_drawer_counter`)
            event.add(`materialism:${classTag}_furniture_wardrobes`, `mcw_tfc_aio:furniture/${wood}_furniture/stripped_${wood}_cupboard_counter`)
            event.add(`materialism:${classTag}_furniture_bookshelves`, `mcw_tfc_aio:furniture/${wood}_furniture/${wood}_bookshelf`)
            event.add(`materialism:${classTag}_furniture_bookshelves`, `mcw_tfc_aio:furniture/${wood}_furniture/stripped_${wood}_bookshelf`)
            event.add(`materialism:${classTag}_furniture_lecterns`, `${mod}:wood/lectern/${wood}`)
            event.add(`materialism:${classTag}_furniture_scribing_tables`, `${mod}:wood/scribing_table/${wood}`)
        })
    }
    // Helper function to determine the mod for a given wood
    function getWoodMod(wood) {
        // List of AFC woods (add all afc woods here)
        const afcWoods = [
            'baobab', 'fig', 'hevea', 'tualang', 'teak', 'mahogany', 'cypress', 'eucalyptus', 'ipe', 'ironwood'
            // Add more afc woods as needed
        ];
        return afcWoods.includes(wood) ? 'afc' : 'tfc';
    }
    addClassWoods(event, 'subarctic_tundrafellow', ['pine', 'spruce', 'aspen'])
    addClassWoods(event, 'subarctic_hearthkeeper', ['birch', 'willow'])
    addClassWoods(event, 'subarctic_trailwarden', ['douglas_fir', 'chestnut'])
    addClassWoods(event, 'subarctic_elder', ['oak', 'hickory'])
    addClassWoods(event, 'subarctic_frostborn', ['blackwood', 'white_cedar'])
    addClassWoods(event, 'subarctic_frozen_lord', ['sequoia', 'rosewood'])

    addClassWoods(event, 'temperate_homesteader', ['aspen', 'maple'])
    addClassWoods(event, 'temperate_villager', ['sycamore', 'birch'])
    addClassWoods(event, 'temperate_steward', ['chestnut', 'oak'])
    addClassWoods(event, 'temperate_burgher', ['ash', 'douglas_fir', 'eucalyptus'])
    addClassWoods(event, 'temperate_lawmaker', ['teak', 'blackwood'])
    addClassWoods(event, 'temperate_arbiter', ['rosewood', 'mahogany', 'ipe'])

    addClassWoods(event, 'steppe_nomad', ['willow', 'fig'])
    addClassWoods(event, 'steppe_clansman', ['acacia'])
    addClassWoods(event, 'steppe_outrider', ['cypress', 'eucalyptus'])
    addClassWoods(event, 'steppe_kinlord', ['hickory', 'chestnut'])
    addClassWoods(event, 'steppe_great_rider', ['teak', 'ironwood'])
    addClassWoods(event, 'steppe_windborn', ['rosewood', 'mahogany'])

    addClassWoods(event, 'tropical_mudkin', ['kapok', 'bamboo'])
    addClassWoods(event, 'tropical_palmhand', ['mangrove', 'palm'])
    addClassWoods(event, 'tropical_councilor', ['teak', 'mahogany'])
    addClassWoods(event, 'tropical_raincaller', ['hevea', 'tualang'])
    addClassWoods(event, 'tropical_feathered_noble', ['ipe', 'ironwood'])
    addClassWoods(event, 'tropical_sun_blessed', ['rosewood', 'blackwood', 'baobab'])

    addClassWoods(event, 'desert_wayfarer', ['palm', 'acacia'])
    addClassWoods(event, 'desert_sandborn', ['fig', 'willow'])
    addClassWoods(event, 'desert_waterkeeper', ['cypress', 'sycamore'])
    addClassWoods(event, 'desert_trade_lord', ['white_cedar', 'eucalyptus'])
    addClassWoods(event, 'desert_dune_elder', ['ipe', 'blackwood'])
    addClassWoods(event, 'desert_sunward', ['mahogany', 'rosewood'])

    addClassWoods(event, 'mountain_stonebound', ['pine', 'spruce'])
    addClassWoods(event, 'mountain_cliffdweller', ['birch', 'aspen'])
    addClassWoods(event, 'mountain_deepdelver', ['douglas_fir', 'oak'])
    addClassWoods(event, 'mountain_runespeaker', ['hickory', 'chestnut', 'eucalyptus'])
    addClassWoods(event, 'mountain_skyforged', ['teak', 'ironwood'])
    addClassWoods(event, 'mountain_stormcaller', ['sequoia', 'rosewood', 'mahogany'])

})

ServerEvents.tags('item', event => {
    event.add('materialism:powders/copper', 'tfc:powder/native_copper')
    event.add('materialism:powders/copper', 'tfc:powder/malachite')
    event.add('materialism:powders/copper', 'tfc:powder/tetrahedrite')
    event.add('materialism:powders/iron', 'tfc:powder/hematite')
    event.add('materialism:powders/iron', 'tfc:powder/magnetite')
    event.add('materialism:powders/iron', 'tfc:powder/limonite')
    // Add TFC sheets to c:plates tags so TFMG recipes using tags pick them up
    event.add('c:plates/nickel', 'tfc:metal/sheet/nickel')
    event.add('c:plates/lead', 'tfc_metallurgy:metal/sheet/lead')
    event.add('c:plates/cast_iron', 'tfc:metal/sheet/cast_iron')
})

ServerEvents.tags('enchantment', event => {
    event.removeAll('minecraft:in_enchanting_table')
    event.removeAll('minecraft:tradeable')
    event.removeAll('minecraft:on_random_loot')
})