ClientEvents.lang("en_us", event => {
    // Create Big Cannons: nethersteel -> tungsten steel
    event.renameItem('createbigcannons:built_up_nethersteel_cannon_barrel', 'Built-Up Tungsten Steel Cannon Barrel')
    event.renameItem('createbigcannons:built_up_nethersteel_cannon_chamber', 'Built-Up Tungsten Steel Cannon Chamber')
    event.renameItem('createbigcannons:incomplete_nethersteel_screw_breech', 'Incomplete Tungsten Steel Screw Breech')
    event.renameItem('createbigcannons:large_nethersteel_cannon_layer', 'Large Tungsten Steel Cannon Layer')
    event.renameItem('createbigcannons:medium_nethersteel_cannon_layer', 'Medium Tungsten Steel Cannon Layer')
    event.renameItem('createbigcannons:molten_nethersteel_bucket', 'Molten Tungsten Steel Bucket')
    event.renameItem('createbigcannons:nethersteel_block', 'Block of Tungsten Steel')
    event.renameItem('createbigcannons:nethersteel_cannon_barrel', 'Tungsten Steel Cannon Barrel')
    event.renameItem('createbigcannons:nethersteel_cannon_chamber', 'Tungsten Steel Cannon Chamber')
    event.renameItem('createbigcannons:nethersteel_ingot', 'Tungsten Steel Ingot')
    event.renameItem('createbigcannons:nethersteel_nugget', 'Tungsten Steel Nugget')
    event.renameItem('createbigcannons:nethersteel_screw_breech', 'Tungsten Steel Screw Breech')
    event.renameItem('createbigcannons:nethersteel_screw_lock', 'Tungsten Steel Screw Lock')
    event.renameItem('createbigcannons:small_nethersteel_cannon_layer', 'Small Tungsten Steel Cannon Layer')
    event.renameItem('createbigcannons:thick_nethersteel_cannon_chamber', 'Thick Tungsten Steel Cannon Chamber')
    event.renameItem('createbigcannons:unbored_large_nethersteel_cannon_layer', 'Unbored Large Tungsten Steel Cannon Layer')
    event.renameItem('createbigcannons:unbored_medium_nethersteel_cannon_layer', 'Unbored Medium Tungsten Steel Cannon Layer')
    event.renameItem('createbigcannons:unbored_nethersteel_screw_breech', 'Unbored Tungsten Steel Screw Breech')
    event.renameItem('createbigcannons:unbored_small_nethersteel_cannon_layer', 'Unbored Small Tungsten Steel Cannon Layer')
    event.renameItem('createbigcannons:unbored_very_large_nethersteel_cannon_layer', 'Unbored Very Large Tungsten Steel Cannon Layer')
    event.renameItem('createbigcannons:unbored_very_small_nethersteel_cannon_layer', 'Unbored Very Small Tungsten Steel Cannon Layer')
    event.renameItem('createbigcannons:very_large_nethersteel_cannon_layer', 'Very Large Tungsten Steel Cannon Layer')
    event.renameItem('createbigcannons:very_small_nethersteel_cannon_layer', 'Very Small Tungsten Steel Cannon Layer')
    event.add('tag.c.ingots.nethersteel', 'Tungsten Steel Ingots')
    event.add('tag.c.nuggets.nethersteel', 'Tungsten Steel Nuggets')
    event.add('tag.c.storage_blocks.nethersteel', 'Tungsten Steel Blocks')

    // Change the display name of a block
    event.renameItem('create:andesite_casing', 'Aluminum casing')
    event.renameItem('create:andesite_bars', 'Aluminum Bars')
    event.renameItem('create_new_age:redstone_magnet', 'Weak Ferrite Magnet')
    event.renameItem('create_new_age:layered_magnet', 'Strong Ferrite Magnet')
    event.renameItem('create_new_age:fluxuated_magnetite', 'Alnico Magnet')
    event.renameItem('create_new_age:netherite_magnet', 'Neodymium Magnet')
    // event.renameItem('tfmg:capacitor', 'Lead-Acid Battery') // item removed/renamed in TFMG 1.21
    // event.renameItem('tfmg:accumulator', 'Lithium Battery') // Let's use accumulators for both battery types
    event.renameItem('create_new_age:radioactive_thorium', 'Fissible Material')
    event.renameItem('createsifter:andesite_mesh', 'Stainless Steel Mesh')
    event.renameItem('createsifter:custom_mesh', 'Titanium Mesh')
    event.renameItem('create:andesite_ladder', 'Aluminum Ladder')
    event.renameItem('create:andesite_bars', 'Aluminum Bars')
    event.renameItem('create:andesite_scaffolding', 'Aluminum Scaffolding')
    event.renameItem('create:andesite_door', 'Aluminum Door')
    event.renameItem('createdeco:andesite_window', 'Aluminum Window')
    event.renameItem('createdeco:andesite_window_pane', 'Aluminum Window Pane')
    event.renameItem('createdeco:iron_window', 'Stainless Steel Window')
    event.renameItem('createdeco:andesite_door', 'Aluminum Door')
    event.renameItem('createdeco:locked_andesite_door', 'Locked Aluminum Door')
    event.renameItem('createdeco:andesite_trapdoor', 'Aluminum Trapdoor')
    event.renameItem('bellsandwhistles:andesite_bogie_steps', 'Aluminum Steps')
    event.renameItem('bellsandwhistles:andesite_grab_rails', 'Aluminum Grab Bars')
    event.renameItem('bellsandwhistles:andesite_door_step', 'Aluminum Door Step')
    event.renameItem('createdeco:andesite_sheet_metal', 'Aluminum Sheet Metal')
    event.renameItem('createdeco:andesite_support', 'Aluminum Support')
    event.renameItem('createdeco:andesite_bars', 'Aluminum Bars')
    event.renameItem('createdeco:andesite_bars_overlay', 'Aluminum Bars Overlay')
    event.renameItem('createdeco:andesite_mesh_fence', 'Aluminum Mesh Fence')
    event.renameItem('createdeco:andesite_sheet', 'Aluminum Sheet')
    event.renameItem('createdeco:andesite_hull', 'Aluminum Hull')
    event.renameItem('createdeco:andesite_support_wedge', 'Aluminum Support Wedge')
    event.renameItem('createdeco:andesite_catwalk', 'Aluminum Catwalk')
    event.renameItem('createdeco:andesite_catwalk_railing', 'Aluminum Catwalk Railing')
    event.renameItem('createdeco:andesite_catwalk_stairs', 'Aluminum Catwalk Stairs')
    event.renameItem('createdeco:blue_andesite_lamp', 'Blue Aluminum Lamp')
    event.renameItem('createdeco:green_andesite_lamp', 'Green Aluminum Lamp')
    event.renameItem('createdeco:red_andesite_lamp', 'Red Aluminum Lamp')
    event.renameItem('createdeco:yellow_andesite_lamp', 'Yellow Aluminum Lamp')
    event.renameItem('bellsandwhistles:andesite_pilot', 'Aluminum Pilot')
    // Andesite gauge tracks are now stone-based -> drop "Andesite" from the name
    event.renameItem('railways:track_create_andesite_narrow', 'Narrow Train Track')
    event.renameItem('railways:track_create_andesite_wide', 'Wide Train Track')
    event.renameItem('railways:track_incomplete_create_andesite_narrow', 'Incomplete Narrow Track')
    event.renameItem('railways:track_incomplete_create_andesite_wide', 'Incomplete Wide Track')
    // event.renameItem('interiors:kelp_chair', 'Rubber Chair') // item removed/renamed in Interiors 1.21
    // event.renameItem('interiors:kelp_floor_chair', 'Rubber Floor Chair')
    // event.renameItem('interiors:kelp_seat', 'Rubber Seat')
    event.renameItem('tfmg:cinderflourblock', 'Red Cinderblock')
    event.renameItem('tfmg:cinderflour_block', 'Red Cinder Block')
    // Rename netherite butchery tools to tungsten steel
    event.renameItem('butchery:netherite_cleaver', 'Tungsten Steel Cleaver')
    event.renameItem('butchery:netherite_hacksaw', 'Tungsten Steel Hacksaw')
    event.renameItem('butchery:netherite_hammer', 'Tungsten Steel Hammer')
    event.renameItem('butchery:netherite_skinning_knife', 'Tungsten Steel Skinning Knife')
    
    event.renameItem('aeronautics:andesite_propeller', 'Steel Propeller')

});