#Time for a Xoonglin to mate again, in ticks.
#Range: 0 ~ 24000
xoonglinMatingCooldown = 6000
#This will force loading the chunks where a Xoonglin is present. ATTENTION: This can highly damage the performance.
keepXoonglinsLoaded = true

[homeDetection]
	#Maximum height of a block that is part of a Xoonglin house.
	#Range: -64 ~ 319
	maxHouseSize = 319
	#Maximum amount of blocks that the floor of a Xoonglin house can have.
	#Range: 9 ~ 1000
	maxFloorSize = 100

[needs]
	#Minimum distance at which a Xoonglin can interact with containers.
	#Range: 0.1 ~ 5.0
	closeEnoughDistanceToContainer = 3.0
	#How long to check again if supplies are not present, in ticks.
	#Range: 40 ~ 5000
	supplyCooldown = 200

[jobs]
	#The distance from the home entrance that is considered near enough for working at home.
	#Range: 1.0 ~ 50.0
	homeWorkRadius = 3.0

