#Whether to prevent island and hotspot volcanoes outside the "world".
keepIslandsAndHotspotVolcanoesInside = true
#Whether to limit world generation to fit the Craster Parabolic map projection.
craterParabolicMapProjection = true
#Whether to teleport players crossing the 180° to the other side of the world.
crossing180MeridianTeleport = true
