#Whether to limit world generation to fit the current map projection. Similar to "Finite Continents".
limitWorldGenerationOutsideMapProjection = true
#What map/world projection to use on new worlds.
#Allowed Values: CRASTER_PARABOLIC
mapProjection = "CRASTER_PARABOLIC"
#Whether to prevent island and hotspot volcanoes outside the "world".
keepIslandsAndHotspotVolcanoesInside = true
