#The average point for temperature, the not too warm and not too cool point
# Default: 15
# Range: 0 ~ 30
averageTemperature = 15
#The point where warmth starts to affect the screen, but only mildly
# Default: 20.0
# Range: 5.0 ~ 35.0
hotThreshold = 20.0
#The point where cold starts to affect the screen, but only mildly
# Default: 10.0
# Range: -15.0 ~ 25.0
coolThreshold = 10.0
#The point where warmth starts to hurt the player.json
# Default: 25.0
# Range: 15.0 ~ 45.0
burnThreshold = 25.0
#The point where cold starts to hurt the player.json
# Default: 5.0
# Range: -15.0 ~ 15.0
freezeThreshold = 5.0
#How quickly player.json wetness changes towards the target environment wetness
# Default: 1.0
# Range: 0.0 ~ 50.0
wetnessChangeSpeed = 1.0
#How quickly player.json temperature changes towards the target environment temperature
# Default: 1.0
# Range: 0.0 ~ 50.0
temperatureChangeSpeed = 1.0
#How quickly player.json temperature changes towards the target environment temperature when it's beneficial to do so
# Default: 4.0
# Range: 0.0 ~ 50.0
goodTemperatureChangeSpeed = 4.0
#How quickly player.json temperature changes towards the target environment temperature when it's not beneficial
# Default: 1.0
# Range: 0.0 ~ 50.0
badTemperatureChangeSpeed = 1.0
#How much do items in the forge:hot_ingots tag modify the temperature of the player
# Default: 1.0
# Range: 0.0 ~ 3.4028234663852886E38
hotIngotTemperature = 1.0
