[temperature]
	#X offset of the main temperature status indicator
	# Default: 0.0
	# Range: -999.0 ~ 999.0
	x = 0.0
	#Y offset of the main temperature status indicator
	# Default: 0.0
	# Range: -999.0 ~ 999.0
	y = 0.0

[shelter]
	#X offset of the shelter indicator
	# Default: 0.0
	# Range: -999.0 ~ 999.0
	x = 0.0
	#Y offset of the shelter indicator
	# Default: 0.0
	# Range: -999.0 ~ 999.0
	y = 0.0

[healthDrain]
	#X offset of the health drain indicator
	# Default: 0.0
	# Range: -999.0 ~ 999.0
	x = 0.0
	#Y offset of the health drain indicator
	# Default: 0.0
	# Range: -999.0 ~ 999.0
	y = 0.0

[hungerDrain]
	#X offset of the hunger drain indicator
	# Default: 0.0
	# Range: -999.0 ~ 999.0
	x = 0.0
	#Y offset of the hunger drain indicator
	# Default: 0.0
	# Range: -999.0 ~ 999.0
	y = 0.0

[thirstDrain]
	#X offset of the thirst drain indicator
	# Default: 0.0
	# Range: -999.0 ~ 999.0
	x = 0.0
	#Y offset of the thirst drain indicator
	# Default: 0.0
	# Range: -999.0 ~ 999.0
	y = 0.0

[wetnessIndicator]
	#X offset of the wetness indicator
	# Default: 0.0
	# Range: -999.0 ~ 999.0
	x = 0.0
	#Y offset of the wetness indicator
	# Default: 0.0
	# Range: -999.0 ~ 999.0
	y = 0.0

[textStatus]
	#X offset of the text status (when shift is pressed)
	# Default: 0.0
	# Range: -999.0 ~ 999.0
	x = 0.0
	#Y offset of the text status (when shift is pressed)
	# Default: 0.0
	# Range: -999.0 ~ 999.0
	y = 0.0
