[general]
	#This sets whether an item that contains a fluid will have a tooltip that they are gaseous, too hot or too cold.
	enableTooltips = true
	#This sets whether gaseous effect for a fluid should be enabled.
	enableGaseous = true
	#If true, then items that melt into a fluid will create a puddle below you. Potentially dangerous if this is a molten metal, lava or equivalent.
	toggleFluidPuddle = true
	#If true, players yeet hot or cold items from their hands.
	yeet = true
	#This sets the temperature when a hot object should start burning the player (in celsius).
	# Default: 300.0
	# Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	hotTemperature = 300.0
	#This sets the temperature when a cold object should add effects to the player (in celsius).
	# Default: -20.0
	# Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	coldTemperature = -20.0
	#This sets the temperature when a hot fluid should start burning the player (in kelvin).
	# Default: 1300.0
	# Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	hotFluidTemperature = 1300.0
	#This sets the temperature when a cold fluid should add effects to the player (in kelvin).
	# Default: 273.0
	# Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	coldFluidTemperature = 273.0
	#Modifier for how much the offhand item should heat up when holding hot items. Holding multiple hot items will heat your insulating items faster!
	# Default: 2.0
	# Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	itemTemperatureModifier = 2.0
	#How often the heat of your tongs, mittens or potholders should increase. Higher value -> slower. Too high and items won't heat up.
	# Default: 1
	# Range: > 1
	itemHeatTimeInterval = 1
	#How often the durability of your tongs, mittens or potholders should take damage. Higher value -> slower. Holding multiple hot items will damage your insulating items faster!
	# Default: 10
	# Range: > 1
	itemDamageTimeInterval = 10
	#Durability for wooden tongs.
	# Default: 200
	# Range: > 0
	woodenTongsDurability = 200
	#Durability for potholders.
	# Default: 800
	# Range: > 0
	potholderDurability = 800
	#Durability for mittens.
	# Default: 1700
	# Range: > 0
	mittenDurability = 1700
