[General]
	#Should burnt blocks have a darkening tint-effect applied? Needs a chunk-update to take effect! (Press F3 + A to reload chunks). True = tint enabled.
	toggleBurnTint = true
	#Show volcano particle effects.
	showVolcanoParticles = true
	#Enable screen shake during tremors
	enableScreenShake = true
	#Enable transparency for particles such as volcano smoke, smoke trails etc.
	enableAlphaForParticles = true
	#The altitude in blocks at which smoke particles will rise to.
	# Default: 300
	# Range: > 0
	cloudAltitude = 300
	#Render distance for smoke particles.
	# Default: 512.0
	# Range: 0.0 ~ 1.7976931348623157E308
	volcanoSmokePlumeRenderDistance = 512.0
	#Percentage of volcano smoke particles to render.
	# Default: 0.9
	# Range: 0.0 ~ 1.0
	volcanoSmokeCount = 0.9
	#Show geyser trail particle effects (such as lava and water).
	showGeyserTrailParticles = true
	#Percentage of geyser trail particles to render.
	# Default: 0.8
	# Range: 0.0 ~ 1.0
	geyserTrailCount = 0.8
	#Show smoke trail particle effects.
	#For example as seen on pyroclastic bombs.
	showSmokeTrailParticles = true
	#Percentage of smoke trail particles to render.
	#For example as seen on pyroclastic bombs.
	# Default: 0.8
	# Range: 0.0 ~ 1.0
	smokeTrailCount = 0.8
	#Show pyroclastic flow particle effects.
	showPyroclasticFlowParticles = true
	#Percentage of pyroclastic flow particles to render.
	# Default: 0.9
	# Range: 0.0 ~ 1.0
	pyroclasticFlowCount = 0.9
